Repository Seasoning-Today/backend, pull requests merged in 2024-03, with the labels that each got.

#93 운세 조회 기능 변경
  src/main/java/today/seasoning/seasoning/fortune/controller/FortuneController.java
  src/main/java/today/seasoning/seasoning/fortune/domain/Fortune.java
  src/main/java/today/seasoning/seasoning/fortune/domain/FortuneUserRelation.java
  src/main/java/today/seasoning/seasoning/fortune/domain/FortuneUserRelationRepository.java
  src/main/java/today/seasoning/seasoning/fortune/service/FindFortuneService.java
  src/main/java/today/seasoning/seasoning/fortune/service/FortuneService.java
Labels: 🔖 Feat

#95 관리자용 API 추가 : 절기 정보 새로고침, 기록장 등록 기간 변경
  src/main/java/today/seasoning/seasoning/solarterm/controller/SolarTermController.java
  src/main/java/today/seasoning/seasoning/solarterm/controller/YearDto.java
  src/main/java/today/seasoning/seasoning/solarterm/service/SolarTermService.java
Labels: 🔖 Feat

#96 기록장 서비스 로직 코드 정리
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleRepository.java
  src/main/java/today/seasoning/seasoning/article/domain/CustomArticleRepository.java
  src/main/java/today/seasoning/seasoning/article/domain/CustomArticleRepositoryImpl.java
  src/main/java/today/seasoning/seasoning/article/dto/FindCollageCommand.java
  src/main/java/today/seasoning/seasoning/article/dto/FindCollageResponse.java
  src/main/java/today/seasoning/seasoning/article/dto/FindCollageResult.java
  src/main/java/today/seasoning/seasoning/article/dto/FindMyArticlesByYearResponse.java
  src/main/java/today/seasoning/seasoning/article/dto/FindMyArticlesByYearResult.java
  src/main/java/today/seasoning/seasoning/article/service/ArticleLikeService.java
  src/main/java/today/seasoning/seasoning/article/service/DeleteArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/FindArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/FindCollageService.java
  src/main/java/today/seasoning/seasoning/article/service/FindMyArticlesByYearService.java
  src/main/java/today/seasoning/seasoning/article/service/RegisterArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/UpdateArticleService.java
Labels: 🔖 Refactor

#98 fix: 기록장 좋아요 취소 오류 해결
  src/main/java/today/seasoning/seasoning/article/service/ArticleLikeService.java
Labels: 🔖 Fix

#99 최초 랜덤 아이디 생성값을 소문자로 변경
  src/main/java/today/seasoning/seasoning/user/domain/User.java
Labels: 🔖 Refactor

#101 통합 테스트 작성 : 기록장 좋아요 등록
  src/test/java/today/seasoning/seasoning/BaseIntegrationTest.java
  src/test/java/today/seasoning/seasoning/article/integration/RegisterArticleLikeIntegrationTest.java
Labels: 🔖 Test

#103 기록장 암호화 재적용 외 기타 작업
  src/main/java/today/seasoning/seasoning/SeasoningApplication.java
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
  src/main/java/today/seasoning/seasoning/common/cipher/CipherUtil.java
  src/main/java/today/seasoning/seasoning/common/exception/GlobalExceptionHandler.java
  src/test/java/today/seasoning/seasoning/CipherUtilTest.java
Labels: 🔖 Refactor

#104 기록장 본문 암호화 배포 문제 해결
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
Labels: 🔖 Fix

#105 기록장 좋아요 서비스 로직 분리 및 기록장 좋아요 취소 통합 테스트 작성
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/service/ArticleLikeService.java
  src/main/java/today/seasoning/seasoning/article/service/CancelArticleLikeService.java
  src/main/java/today/seasoning/seasoning/article/service/RegisterArticleLikeService.java
  src/main/java/today/seasoning/seasoning/article/service/ValidateArticleLikePolicy.java
  src/main/java/today/seasoning/seasoning/article/service/ValidateArticleLikePolicyImpl.java
  src/test/java/today/seasoning/seasoning/article/integration/CancelArticleLikeIntegrationTest.java
Labels: 🔖 Refactor, 🔖 Test

#107 중앙 집중식 로깅 구현
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🔖 Refactor

#108 콜라주 조회 통합 테스트 작성
  src/test/java/today/seasoning/seasoning/article/service/FindCollageServiceTest.java
Labels: 🔖 Test

#109 통합 테스트 작성 : 연도별 기록장 조회
  src/test/java/today/seasoning/seasoning/article/integration/FindCollageIntegrationTest.java
  src/test/java/today/seasoning/seasoning/article/integration/FindMyArticlesByYearIntegrationTest.java
Labels: 🔖 Test
